version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strongPassword
      MYSQL_DATABASE: library_system